"""add_anki_spaced_repetition_fields

Revision ID: 036ec3217785
Revises: 428423f6788d
Create Date: 2026-01-11 23:00:26.483299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036ec3217785'
down_revision: Union[str, Sequence[str], None] = '428423f6788d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('ease_factor', sa.Float(), nullable=False, server_default='2.5'))
    op.add_column('user_progress', sa.Column('interval_days', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_progress', sa.Column('review_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progress', 'review_count')
    op.drop_column('user_progress', 'interval_days')
    op.drop_column('user_progress', 'ease_factor')
    # ### end Alembic commands ###
