"""initial schema with supabase auth and language enum

Revision ID: 40b1440b17d7
Revises: 
Create Date: 2026-01-02 21:04:02.316258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40b1440b17d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty'), nullable=False),
    sa.Column('pattern', sa.String(length=50), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('constraints', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_number'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('problem_languages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.Enum('PYTHON', 'JAVASCRIPT', name='language'), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=False),
    sa.Column('reference_solution', sa.Text(), nullable=False),
    sa.Column('function_signature', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_problem_languages_language', 'problem_languages', ['language'], unique=False)
    op.create_index('ix_problem_languages_problem_id', 'problem_languages', ['problem_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('language', sa.Enum('PYTHON', 'JAVASCRIPT', name='language'), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('runtime_ms', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submissions_user_problem', 'submissions', ['user_id', 'problem_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_cases_problem_id', 'test_cases', ['problem_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('times_solved', sa.Integer(), nullable=False),
    sa.Column('last_solved_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('is_mastered', sa.Boolean(), nullable=False),
    sa.Column('show_again', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_progress_next_review_date', 'user_progress', ['next_review_date'], unique=False)
    op.create_index('ix_user_progress_problem_id', 'user_progress', ['problem_id'], unique=False)
    op.create_index('ix_user_progress_user_id', 'user_progress', ['user_id'], unique=False)
    op.create_index('ix_user_progress_user_problem', 'user_progress', ['user_id', 'problem_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_progress_user_problem', table_name='user_progress')
    op.drop_index('ix_user_progress_user_id', table_name='user_progress')
    op.drop_index('ix_user_progress_problem_id', table_name='user_progress')
    op.drop_index('ix_user_progress_next_review_date', table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index('ix_test_cases_problem_id', table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index('ix_submissions_user_problem', table_name='submissions')
    op.drop_table('submissions')
    op.drop_index('ix_problem_languages_problem_id', table_name='problem_languages')
    op.drop_index('ix_problem_languages_language', table_name='problem_languages')
    op.drop_table('problem_languages')
    op.drop_table('problems')
    # ### end Alembic commands ###
