"""remove_is_hidden_and_failed_is_hidden

Revision ID: f9b5f87f0cb2
Revises: 036ec3217785
Create Date: 2026-01-15 21:34:53.759840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b5f87f0cb2'
down_revision: Union[str, Sequence[str], None] = '036ec3217785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
