"""Add user_code table for code persistence

Revision ID: fb7f174fb2a3
Revises: 2bbd7badbd70
Create Date: 2026-01-10 18:28:46.255968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7f174fb2a3'
down_revision: Union[str, Sequence[str], None] = '2bbd7badbd70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_code',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_code_user_problem', 'user_code', ['user_id', 'problem_id'], unique=False)
    op.create_index('ix_user_code_unique', 'user_code', ['user_id', 'problem_id', 'language'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_code_unique', table_name='user_code')
    op.drop_index('idx_user_code_user_problem', table_name='user_code')
    op.drop_table('user_code')
    # ### end Alembic commands ###
